repo: https://github.com/madler/zlib.git
ver: 1.3
tag_prefix: v
tag_dot2ul: false
cb_tool: cmake
options: -DZLIB_BUILD_EXAMPLES=OFF
options_unix: -DZLIB_BUILD_SHARED=OFF
options_msw: -DZLIB_BUILD_STATIC=OFF
