repo: https://github.com/libjpeg-turbo/libjpeg-turbo.git
ver: 3.0.1
tag_prefix: ''
tag_dot2ul: false
cb_tool: cmake
targets: win32,osx,linux,ios,android,tvos
options: -DWITH_SIMD=ON -DWITH_JPEG8=ON -DENABLE_SHARED=OFF -DWITH_TURBOJPEG=OFF -DWITH_TESTS=OFF -DWITH_TOOLS=OFF
options_msw: -DWITH_CRT_DLL=ON
