#
# Copyright (c) 2021 Bytedance Inc.
#

name: linux-ci

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ dev ]
    paths:
      - .github/workflows/linux-ci.yml
      - 1k/build.sh
      - 1k/buildall.sh

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  android:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Run a job for each of the specified target architectures:
    strategy:
      matrix:
        arch:
          - arm
          - arm64
          - x86
    env:
      BUILD_TARGET: android
      BUILD_ARCH: ${{ matrix.arch }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build
        run: source ./1k/buildall.sh ${BUILD_TARGET} ${BUILD_ARCH}

      - name: Upload prebuilt files
        uses: actions/upload-artifact@v2
        with:
          path: ./${{ env.INSTALL_ROOT }}/**
          name: ${{ env.INSTALL_ROOT }}

  linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      BUILD_TARGET: linux
      BUILD_ARCH: x86_64

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Build
        run: source ./1k/buildall.sh ${BUILD_TARGET} ${BUILD_ARCH}

      - name: Upload prebuilt files
        uses: actions/upload-artifact@v2
        with:
          path: ./${{ env.INSTALL_ROOT }}/**
          name: ${{ env.INSTALL_ROOT }}
